version: "3.9"

services:
  smartdoc-reviewer:
    build: .
    container_name: smartdoc-reviewer

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    env_file:
      - .env

    restart: unless-stopped